creationTime: 2022-08-04T20:43:45.853Z
format: Docker
exposedPorts: ['3000']
from:
  image: eclipse-temurin:11-jre
  platforms:
  - {architecture: arm64, os: linux}
  - {architecture: amd64, os: linux}
kind: BuildFile
entrypoint: [java, -jar, ring-sink.jar]
layers:
  properties: {timestamp: !!timestamp '2022-08-04T20:43:45.853Z'}
  entries:
  - name: app
    files:
    - {src: target\ring-sink-1.0.10-standalone.jar, dest: /app/ring-sink.jar}
workingDirectory: /app
apiVersion: jib/v1alpha1
